edit-menu:
  title: "&8» &2Editing item ID: &c%item_id%"
  fill-item:
    material: "GREEN_STAINED_GLASS_PANE"
    name: "&r"
    lore:
      - ""

  buy-price-button:
    material: "PAPER"
    name: "&aBuy price"
    lore:
      - "&8» &aCurrent buy price: &2%current_buy_price%"
      - "&8» &aNew buy price: &2%new_buy_price%"
      - ""
      - "&7Click to set the new price."

  sell-price-button:
    material: "PAPER"
    name: "&cSell price"
    lore:
      - "&8» &aCurrent sell price: &2%current_sell_price%"
      - "&8» &aNew sell price: &2%new_sell_price%"
      - ""
      - "&7Click to set the new price."

messages:
  successfully-set: "&2Successfully updated the new price."
  no-permission: "&cYou do not have permission to do that."
  reloaded: "&aSuccessfully reloaded the config."