edit-menu:
  title: "&8» &2Editing item ID: &c%item_id%"
  fill-item:
    material: "GREEN_STAINED_GLASS_PANE"
    name: "&r"
    lore:
      - ""

  buy-price-button:
    material: "PAPER"
    name: "&aBuy price"
    lore:
      - "&8» &aCurrent buy price: &2%current_buy_price%"
      - "&8» &aNew buy price: &2%new_buy_price%"
      - ""
      - "&7Click to set the new price."

  sell-price-button:
    material: "PAPER"
    name: "&cSell price"
    lore:
      - "&8» &aCurrent sell price: &2%current_sell_price%"
      - "&8» &aNew sell price: &2%new_sell_price%"
      - ""
      - "&7Click to set the new price."

  sell-price-adjust-buttons:
    button-1:
      size: 1
      name: '&2$%amount%'
      amount: '0.1'
      shift-multiplier: 2
      material: 'RED_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'
    button-2:
      size: 2
      name: '&2$%amount%'
      amount: '1'
      shift-multiplier: 2
      material: 'RED_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'
    button-3:
      size: 3
      name: '&2$%amount%'
      amount: '10'
      shift-multiplier: 2
      material: 'RED_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'

  buy-price-adjust-buttons:
    button-1:
      size: 1
      name: '&2$%amount%'
      amount: '0.1'
      shift-multiplier: 2
      material: 'LIME_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'
    button-2:
      size: 2
      name: '&2$%amount%'
      amount: '1'
      shift-multiplier: 2
      material: 'LIME_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'
    button-3:
      size: 3
      name: '&2$%amount%'
      amount: '10'
      shift-multiplier: 2
      material: 'LIME_CONCRETE'
      lore:
        - '&8» &aLeft click to add %amount%'
        - '&8» &aRight click to subtract %amount%'
        - ''
        - '&7Shift-click to multiply by 2'

messages:
  successfully-set: "&2Successfully updated the new price."
  no-permission: "&cYou do not have permission to do that."
  reloaded: "&aSuccessfully reloaded the config."