name: ShopGUIPlusEditor
main: me.m0dii.shopguipluseditor.ShopGUIPlusEditor
description: ShopGUIPlusEditor
version: 1.3.0
api-version: 1.13
author: M0dii
softdepend: [ShopGUIPlus]
commands:
  shopguipluseditor:
    description: Main command.
    aliases: [sgpe, sge, shopguieditor]
permissions:
  shopguipluseditor.use:
    description: Permission to use the editor.
    default: op
  shopguipluseditor.command.reload:
    description: Permission to reload the config.
    default: op